# Generated by Django 4.1.2 on 2022-10-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name_in_database', models.CharField(default='', max_length=30)),
                ('stock_symbol_in_database', models.CharField(default='', max_length=30)),
                ('stock_current_price_in_database', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_profit_in_database', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_buy_price_in_database', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock_amount_in_database', models.IntegerField()),
                ('stock_created_time_in_database', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
