# Generated by Django 4.1.2 on 2022-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crypto_currency_directory_mutual_fund_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutual_fund_directory',
            name='mutual_fund_type_in_database',
            field=models.CharField(default='', max_length=30),
        ),
    ]
