# Generated by Django 4.1.2 on 2022-11-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created_time', models.DateTimeField(auto_now_add=True)),
                ('stocks_investment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stocks_return', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stocks_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mutual_funds_investment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mutual_funds_return', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mutual_funds_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
